webtalk_init -webtalk_dir F:/Proyectos/Arquitectura de Computadoras/Primer Departamental/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/tbESCOMIPS_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 29 16:56:30 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb73d8fe-e294-422a-ad7a-8b382ef49536" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1f935db0c01f45b2bb02618c333a9562" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "135" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1635 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2709251602 -regid "" -xml F:/Proyectos/Arquitectura de Computadoras/Primer Departamental/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/tbESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Proyectos/Arquitectura de Computadoras/Primer Departamental/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/tbESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Proyectos/Arquitectura de Computadoras/Primer Departamental/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/tbESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
